GET http://localhost:8080/attach/adm/list?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjUyNTYxODI4LCJleHAiOjE2NTI1NjU0MjgsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiQURNSU4ifQ.J9NoF-Hc8lWBajiGReVTbPSRQs61K0ffRUY6E7wVE2c

###
DELETE http://localhost:8080/attach/adm/delete/348f2162-f161-4167-990e-28d0af957f62
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjUyNTYxODI4LCJleHAiOjE2NTI1NjU0MjgsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiQURNSU4ifQ.J9NoF-Hc8lWBajiGReVTbPSRQs61K0ffRUY6E7wVE2c