POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "tosha@yandex.com",
  "password": "toshmat"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "akobir.abduganiev@ya.ru",
  "password": "akobir"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "akobir.abduganiev@yandex.com",
  "password": "Alibek"
}

