POST http://localhost:8080/channel/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjUyODE2NjY2LCJleHAiOjE2NTI4MjAyNjYsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.zVqRKP6vA6Hfz0C3rqmVaKT3ABsTa7ZTzV-5K97sVT8

{
  "name": "TOPLES",
  "description": "Albatta eng yaxshi kanallardan biri hisoblanadi!"
}

###
PUT http://localhost:8080/channel/08aeb3de-8dda-4f5c-b5b5-d34d0bbf7db7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNTUzOTYzLCJleHAiOjE2NTI1NTc1NjMsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.YgpEEoo1uzOPPVvzJWw9RRcWG_m542QvgCccHFlWwWs

{
  "name": "TOPLES",
  "description": "Juda ham yaxshi kanal obuna bo'lishni unutmang!"
}

###
PUT http://localhost:8080/channel/update-photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjUyNTUzODMwLCJleHAiOjE2NTI1NTc0MzAsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.6EgQR0-0AKNXQYslTlgz5pfOy1v082DE8owsp5ATIF4

{
  "photoId": "83a2b75e-97a5-4dc2-bb2a-5b41070acda9",
  "channelKey": "08aeb3de-8dda-4f5c-b5b5-d34d0bbf7db7"
}

###
PUT http://localhost:8080/channel/update-banner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjUyNTU2MDE5LCJleHAiOjE2NTI1NTk2MTksImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.3n5vbSV9AnZ-M1R78XtjmSyvBpJyXayF28HhTmgeRWE

{
  "photoId": "83a2b75e-97a5-4dc2-bb2a-5b41070acda9",
  "channelKey": "08aeb3de-8dda-4f5c-b5b5-d34d0bbf7db7"
}

###
GET http://localhost:8080/channel/adm/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjUyNTU2NzIyLCJleHAiOjE2NTI1NjAzMjIsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiQURNSU4ifQ.kMNAJeMlAJGhTW62bw9lkouxUzjPPdJ0wIp6OowU8sA

###
GET http://localhost:8080/channel/channel-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjUyNTYwMzY3LCJleHAiOjE2NTI1NjM5NjcsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.oCteSSE0aobzRiJe50QtHvJzjs5g-xvIqLNI45XQ-5A

###
GET http://localhost:8080/channel/channel-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNTU4NzkwLCJleHAiOjE2NTI1NjIzOTAsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.0jwfIeg1LvCTnwUHv5aIuomkch1XqRJYuHLE4q_dQVE

###
PUT http://localhost:8080/channel/change-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjUyNTYwMzY3LCJleHAiOjE2NTI1NjM5NjcsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.oCteSSE0aobzRiJe50QtHvJzjs5g-xvIqLNI45XQ-5A

{
  "status" : "ACTIVE",
  "key" : "c9d8b584-59c4-4868-bebd-1fd0c3f40530"
}