POST http://localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjUyMzgyMzY3LCJleHAiOjE2NTIzODU5NjcsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiQURNSU4ifQ.V4VzHNKQufCopBO51piVzRtgKub2ey0G2GoN-hGuLdE

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "email": "tosha@yandex.com",
  "password": "toshmat"
}

###
POST http://localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjUyNDc2NDIyLCJleHAiOjE2NTI0ODAwMjIsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiQURNSU4ifQ.VndYs0jV6btSvtByearrnXlgq-zDZvGWGe2LWWw0-Pk

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali@yandex.com",
  "password": "alijon"
}

###
POST http://localhost:8080/profile/image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNjUyMzQwMjQyLCJleHAiOjE2NTIzNDM4NDIsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.YBvUQIzErHq8jvtTrWQ1Di6asIwfcUSxNPwB6hxCaIw

{
  "id": "fcfbb03a-b900-4a3d-ac0d-bc50617d4992",
  "path": "2022/5/12",
  "extension": "jpg",
  "originName": "Untitled-1.jpg",
  "size": 857459,
  "createdDate": "2022-05-12T11:57:51.5087266"
}

###
PUT http://localhost:8080/profile/adm/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNjEwNTU3LCJleHAiOjE2NTI2MTQxNTcsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.edhZI-oyBoQNlbA0kPsgcQYb9yjFHmCdwfEsHZfZZv4

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "email": "tosha@yandex.com",
  "password": "toshmat"
}

###
PUT http://localhost:8080/profile/update-detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNjExNDc1LCJleHAiOjE2NTI2MTUwNzUsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.AEyQALvNWcFkdt-MxGrTfLWQ3RL8Ykhnh_1V-_eJu3Q

{
  "name": "Alijon",
  "surname": "Alijonov"
}

###
PUT http://localhost:8080/profile/change-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNjIwNjk0LCJleHAiOjE2NTI2MjQyOTQsImlzcyI6InlvdXR1YmUiLCJyb2xlIjoiVVNFUiJ9.nafzD6Zjc-cGCOaU7RsNw4Vm8lDk4G2-gMz1fe6u0Q8

{
  "email": "akobir.abduganiev@yandex.com"
}

###
GET http://localhost:8080/auth/verification/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiaWF0IjoxNjUyNjIzMzcyLCJleHAiOjE2NTI2MjY5NzIsImlzcyI6InlvdXR1YmUiLCJlbWFpbCI6ImFrb2Jpci5hYmR1Z2FuaWV2QHlhbmRleC5jb20ifQ.cF5FwuxSbweo3Ha397hlMoxD7anKq-0d_LeHKXPifd8
